# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - login-apii

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1052ee5bb11a4ec18cb43012e16509cd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_293a7d01f1794f3089c798152c42fba1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1052ee5bb11a4ec18cb43012e16509cd }}/login-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'login-apii'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5df4c8cdd0b944f087be8c12e96f48db }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1052ee5bb11a4ec18cb43012e16509cd }}/login-api:${{ github.sha }}'